### ISSUE TITLE
Embargo compatability

### ISSUE THREAD

**Issue by CodyCBakerPhD** [flatironinstitute/neurosift#112]
It's possible to attach DANDI credentials with curl API calls to DANDI to grant permissions to access embargo'd contents; I think in theory it ought to work here as well

So I'd like to request the ability (or instructions if already an ability) to run Neurosift on an embargoed DANDI set

**Comment by magland** [comment]
Thanks @CodyCBakerPhD

I'll work on this soon - we will definitely need to support embargoed datasets.

**Comment by magland** [comment]
Here's an example of a view of an nwb asset from an embargoed dandiset
https://flatironinstitute.github.io/neurosift/?p=/nwb&url=https://dandi-api-staging-embargo-dandisets.s3.amazonaws.com/210194/blobs/945/44c/94544c84-0a89-4b16-9cad-b72af6d67552

As expected, it doesn't load, because access is denied to the s3 bucket. I don't expect to be able to easily get that to download directly. But maybe there's hope to get it from this URL:

https://api-staging.dandiarchive.org/api/assets/203750ef-018f-45a4-b8cb-f990b09e20ba/download/

When I curl that, I get `{"detail":"Authentication credentials were not provided."}`

How can I provide my dandi key? Do I use the header?

@CodyCBakerPhD @bendichter

**Comment by bendichter** [comment]
Looking at the dandi API code, you might try this:

https://github.com/dandi/dandi-cli/blob/697af7c43c407ca8ccaa815cecd844d810174cbb/tools/update-assets-on-server#L120

**Comment by magland** [comment]
Oh, I needed to use -L to follow redirects. That seems to be working.

**Comment by magland** [comment]
@bendichter @CodyCBakerPhD 

I DANDI-shared the following embargoed dataset with you
https://gui-staging.dandiarchive.org/dandiset/210194

Here is a neurosift link to one of the nwb assets
https://flatironinstitute.github.io/neurosift?p=/nwb&url=https://api-staging.dandiarchive.org/api/assets/203750ef-018f-45a4-b8cb-f990b09e20ba/download/

...which will not load UNTIL you have provided neurosift with your DANDI "Staging" API Key, which you can now do in the GUI. See the key icon in the top menu.

![image](https://github.com/flatironinstitute/neurosift/assets/3679296/05f1ba73-5792-443d-b66d-99df3e1e55e4)

![image](https://github.com/flatironinstitute/neurosift/assets/3679296/551a7a09-cedd-416a-ac28-054ca6000053)

After you paste in your keys, you can reload the page.

FYI, the keys are stored in local browser storage. It's okay for now, but maybe we'll want to think of a better way.

**Comment by CodyCBakerPhD** [comment]
> ...which will not load UNTIL you have provided neurosift with your DANDI "Staging" API Key, which you can now do in the GUI. See the key icon in the top menu.

For the example you have shared, this works - but was there something specific you had to do for this particular embargoed DANDI set?

I ask because I tried the same approach on another embargoed dataset and it did not work on that (gets stuck on loading and at the bottom says unable to connect to the rtcshare



> FYI, the keys are stored in local browser storage. It's okay for now, but maybe we'll want to think of a better way.

We've been dealing with this on the NWB GUIDE as well, check out https://github.com/NeurodataWithoutBorders/nwb-guide/pull/389

**Comment by magland** [comment]
> For the example you have shared, this works - but was there something specific you had to do for this particular embargoed DANDI set?
> 
> I ask because I tried the same approach on another embargoed dataset and it did not work on that (gets stuck on loading and at the bottom says unable to connect to the rtcshare

It won't work directly from neurosift the menu option in DANDI. That's because the s3 bucket url won't work with the authentication. You need to feed it the DANDI api asset url (the one that ends with /download/). I think we'll want to have that changed in dandiarchive.

**Comment by CodyCBakerPhD** [comment]
> I think we'll want to have that changed in dandiarchive.

I see now - the DANDI menu option gives a URL that points to the S3 directly instead of through the DANDI API

Would you be able to make that change on the DANDI side? Would you like me to make a separate issue for that specifically?

**Comment by magland** [comment]
> I see now - the DANDI menu option gives a URL that points to the S3 directly instead of through the DANDI API
> 
> Would you be able to make that change on the DANDI side? Would you like me to make a separate issue for that specifically?

I'll create a DANDI PR for that.

**Comment by magland** [comment]
Created PR https://github.com/dandi/dandi-archive/pull/1690

**Comment by waxlamp** [comment]
I wanted to offer an alternative solution strategy, a variant of using the `-L` option with `curl`. When `curl` (or any client) follows redirects, what it's doing is receiving a 300-level response, plucking out the `Location` header that contains the redirect URL, and making a subsequent request to that URL. If all you need is the presigned (i.e., duly authorized) S3 URL, you can make the request to the DANDI API asset download endpoint and pull the S3 URL from the response, and then make use of that wherever an S3 URL is needed.

In that case, there's one extra step for the client to perform to get that URL, and then everything after that point should "just work". But I may not be fully understanding the problem here--let me know if I'm missing anything.

**Comment by magland** [comment]
@waxlamp thanks.

Yes I believe that's what I'm doing here, although I might be misunderstanding what you are suggesting:

https://github.com/flatironinstitute/neurosift/blob/c19b83c5daffc98dbd90c6b02ef9de3d5a02f28d/gui/src/pages/NwbPage/NwbPage.tsx#L78

https://github.com/flatironinstitute/neurosift/blob/c19b83c5daffc98dbd90c6b02ef9de3d5a02f28d/gui/src/pages/NwbPage/NwbPage.tsx#L191-L201

https://github.com/flatironinstitute/neurosift/blob/c19b83c5daffc98dbd90c6b02ef9de3d5a02f28d/gui/src/pages/NwbPage/NwbPage.tsx#L203-L216

I do a head request, get the new s3 signed URL and then use that from that point forward.

**Comment by waxlamp** [comment]
Ah, no, you are doing exactly what I suggested.

If I have it right, the remaining problem is that _outgoing_ links from DANDI Archive don't supply the right URL for embargoed assets, and it doesn't make sense in those situations for you to somehow modify that URL into one that works, hence the need for changes in the archive codebase.

I will continue this discussion on your dandi-archive PR--I think I have a simpler solution that introduces less technical debt to that codebase.

Thanks for indulging my questions here.

**Comment by CodyCBakerPhD** [comment]
I believe this has been resolved now?

**Comment by magland** [comment]
Yes thanks @CodyCBakerPhD . Closing
