### ISSUE TITLE
How can I view a remote NWB file hosted somewhere else than Dandi?

### ISSUE THREAD

**Issue by ehennestad** [flatironinstitute/neurosift#129]
> Visualize remote NWB files hosted on non-DANDI web servers or cloud storage.

I did not immediately understand how to do this

**Comment by magland** [comment]
Hi @ehennestad

Right now the requirements are:
* The file needs to be accessible via URL
* The file server needs to support the range header for http requests

Do you have a URL for the NWB file?

Then you just do:

https://flatironinstitute.github.io/neurosift/?p=/nwb&url=https://api.dandiarchive.org/api/assets/37f5e3ce-e1b7-48a7-a47d-6745875eacaa/download/

replacing the url query parameter.

**Comment by ehennestad** [comment]
Awesome! Thanks

**Comment by cdesyoun** [comment]
Hi,
I am working on the NEMAR project, which manages EEG/MEG/iEEG datasets (https://nemsr.org/). 

For testing NWB files, I created sample files on NEMAR storage. These files can be accessed via the download URL, for example, "https://nemar-dev.ucsd.edu/dataexplorer/download?filepath=/expanse/projects/nemar/openneuro/nwb_example_files/download".

When I test this link, https://neurosift.app/?p=/nwb&url="https://nemar-dev.ucsd.edu/dataexplorer/download?filepath=/expanse/projects/nemar/openneuro/nwb_example_files/download", it results in a forever loading page. 

What do I need to know to use the Neurosift interface correctly?

**Comment by ehennestad** [comment]
> When I test this link, [https://neurosift.app/?p=/nwb&url="https://nemar-dev.ucsd.edu/dataexplorer/download?filepath=/expanse/projects/nemar/openneuro/nwb_example_files/download](https://neurosift.app/?p=/nwb&url=%22https://nemar-dev.ucsd.edu/dataexplorer/download?filepath=/expanse/projects/nemar/openneuro/nwb_example_files/download)", it results in a forever loading page.

Is that link for a single file? The URL should point to one file

**Comment by magland** [comment]
Hi @cdesyoun 

I fixed the query parsing for neurosift so that solves one isse.

BTW, your trailing quotation mark was not included in the hyperlink, but now it should work either way.

The other issue is that the server (https://nemar-dev.ucsd.edu) does not seem to have CORS enabled for the https://neurosift.app domain. Is it possible to have the admins to modify the CORS configuration? That should solve the problem. If so, they should enable

HEAD and GET requests for https://neurosift.app and also (for development) http://localhost:4200. It also needs to support Range headers because neurosift requests specific byte ranges.

If it is not possible to modify the CORS configuration in this way, you'll need to set up a proxy server, which involves some effort and which will incur addition expense in terms of bandwidth.

**Comment by cdesyoun** [comment]
> Hi @cdesyoun
> 
> I fixed the query parsing for neurosift so that solves one issue.
> 
> BTW, your trailing quotation mark was not included in the hyperlink, but now it should work either way.
> 
> The other issue is that the server (https://nemar-dev.ucsd.edu) does not have CORS enabled for the https://neurosift.app domain. Is it possible to have the admins modify the CORS configuration? That should solve the problem. If so, they should enable HEAD and GET requests for https://neurosift.app and also (for development) http://localhost:4200. It also needs to support Range requests because neurosift requests specific byte ranges.
> 
> If it is not possible to modify the CORS configuration in this way, you'll need to set up a proxy server, which involves some effort and which will incur addition expense in terms of bandwidth.

Thank you for the quick update, @magland. I will give it a try.

**Comment by magland** [comment]
Sounds good @cdesyoun . Let me know how that goes. I think it would be great to be able to point neurosift to your database.

**Comment by cdesyoun** [comment]
OK, I enabled CORS for both https://neurosift.app and http://localhost:4200 in nemar-dev apache configuration as follows:

`<VirtualHost *:443>
        DocumentRoot /var/www/nemardevc
        TraceEnable off
        RewriteEngine on
        ServerSignature off
        ServerName nemar-dev.ucsd.edu

<IfModule mod_headers.c>
  <FilesMatch "\.*$">
    # Allow CORS for https://neurosift.app and http://localhost:4200
    SetEnvIf Origin "https://neurosift.app$" AccessControlAllowOrigin=$0
    SetEnvIf Origin "http://localhost:4200$" AccessControlAllowOrigin=$0
    Header add Access-Control-Allow-Origin %{AccessControlAllowOrigin}e env=AccessControlAllowOrigin
    Header merge Vary Origin

    # Add other necessary CORS headers
    Header always set Access-Control-Allow-Methods "HEAD, GET, POST, OPTIONS"
    Header always set Access-Control-Allow-Headers "Authorization, Content-Type, X-Requested-With"
  </FilesMatch>
</IfModule>

<IfModule !mod_php5.c>`

I also implemented support for HTTP Range requests. However, when testing the following URL: https://neurosift.app/?p=/nwb&url=https://nemar-dev.ucsd.edu/dataexplorer/downloadfile/download, I encountered the following message in the browser:

"Error loading file: Problem loading file. Unable to load root group. This could be due to a CORS configuration issue."

**Comment by magland** [comment]
@cdesyoun did you get this working? I got an email notification but I don't see the comment here. The link in the notification was working for me....

**Comment by cdesyoun** [comment]
@magland Yes, it is working. I resolved the CORS issue on the nemar-dev site.

**Comment by cdesyoun** [comment]
@magland , When accessing the following URL:

https://neurosift.app/?p=/nwb&url="https://nemar-dev.ucsd.edu/dataexplorer/downloadfile?filepath=/expanse/projects/nemar/openneuro/nwb_example_files/sub-01_ses-20140828T132700_ecephys+image.nwb",

I encountered the error messages below:

Error loading file: Problem loading file. Unable to load root group. This could be due to a CORS configuration issue.

I guess that the file name, "sub-01_ses-20140828T132700_ecephys+image.nwb", is not allowed due to the presence of a plus sign (+).

**Comment by magland** [comment]
@cdesyoun Try pasting this into your browser address bar

https://nemar-dev.ucsd.edu/dataexplorer/downloadfile?filepath=/expanse/projects/nemar/openneuro/nwb_example_files/sub-01_ses-20140828T132700_ecephys+image.nwb

File not found?

**Comment by cdesyoun** [comment]
Thanks for finding the bug, @magland. I noticed that this type of file name is not allowed on the NEMAR site. I will resolve this issue.
