### ISSUE TITLE
Visualizing extensions by their parent classes

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#157]
In this example:

https://neurosift.app/?p=/nwb&url=https://fsbucket-dendro.flatironinstitute.org/dendro-outputs/2d2b13fd/2d2b13fd.ec254350/output&dandisetId=000871&dandisetVersion=draft&dandiAssetId=407d6e5f-2a16-4879-b38f-b74cad7b9e24&st=lindi

There is a neurodata object of type "EllipseEyeTracking". Looking at the spec in the Raw, this type inherits from the core type "EyeTracking." In cases like this, would it be possible to inspect the type hierarchy of the cached spec and try rendering this object with the visualization of the parent class?

This is how NWB Widgets works, not just for extensions but in fact for all neurodata types. If there is no widget defined for that neurodata type, it traverses the line of inheritance looking for the nearest parent for which a widget is defined. In this way, all neurodata objects have at least *some* corresponding widget.

**Comment by magland** [comment]
Okay I'll work on that. But quick question. What's the deal with the different versions in the specifications?

![image](https://github.com/flatironinstitute/neurosift/assets/3679296/3802b8c6-7350-49f7-8010-172c3a6dca82)

Why are multiple versions embedded in the NWB and how do I know which to use?

**Comment by bendichter** [comment]
I really don't know. @rly, should this be permitted?

**Comment by rly** [comment]
Good question. If there are multiple versions, the latest version according to semantic versioning should be used. I don't recall why multiple versions are allowed in the file given that individual neurodata type objects are not versioned and PyNWB/HDMF (and I think MatNWB) just uses the latest. This happens when appending to a file that was written with an older version of NWB than what is currently loaded. Probably the old schema was just not deleted. I created a ticket in HDMF to resolve it.

**Comment by magland** [comment]
@bendichter Neurosift now respects all neurodata type inheritance in the way you suggested.

There is also a new tab called "specifications" that provides tables of all the namespaces, spec-groups, and spec-datasets in the file.

![image](https://github.com/flatironinstitute/neurosift/assets/3679296/56795e3d-c007-420d-9527-21a9fb4a3353)

**Comment by bendichter** [comment]
the widget works great on this example and the spec tab is great too!
