### ISSUE TITLE
announcement: enhanced specifications view

### ISSUE THREAD

**Issue by magland** [flatironinstitute/neurosift#170]
The specifications view now contains clickable links so you can get more detailed information about each namespace, dataset, and group in the specification

![image](https://github.com/flatironinstitute/neurosift/assets/3679296/0d9569f5-4982-41b6-a84c-b157c9c68098)

Thought this would be useful @bendichter

**Comment by bendichter** [comment]
This is great!

<img width="1222" alt="image" src="https://github.com/flatironinstitute/neurosift/assets/844306/80bfef9c-f75c-44e8-8017-5b6a26f26def">

If I'm not mistaken, all the info that is currently in the datasets and groups columns are now in this new modal. If that's the case, I think we might want to remove those columns here, since they are almost always too cut off to be meaningful.

**Comment by magland** [comment]
I think it can be helpful to get a hint of what's there... and at least tell whether or not there is something present.
