### ISSUE TITLE
Use NWB object inheritance 

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#18]
In NWB Widgets, we leverage object inheritance to improve coverage of NWB data types. For example, you may have a custom data type that inherits from `ElectricalSeries`, which inherits from `TimeSeries`, which inherits from `NWBContainer`. For each object, NWB Widgets will go back through the mro and find the class for which a visualization is defined. This technique provides pretty good coverage of types, even for extension we have never seen, or data types that do not have their own visualization. For example, just showing traces over time tends to be a pretty good visualization for just about any timeseries. It works really well for extensions. You may not have a visualizer for an extension, but if you know that extension inherits from a known type, you may be able to just fall back to the visualizer for that known type. This would work really well for example for RoiResponseSeries, which can be viewed the exact same way you are currently showing ElectricalSeries

**Comment by magland** [comment]
@bendichter How can we know which neurodata types inherit from others?

**Comment by bendichter** [comment]
Good question. In Python it's simply `obj.__class__.__mro__` which returns something like:

```python
(pynwb.ecephys.ElectricalSeries,
 pynwb.base.TimeSeries,
 pynwb.core.NWBDataInterface,
 pynwb.core.NWBContainer,
 pynwb.core.NWBMixin,
 hdmf.container.Container,
 hdmf.container.AbstractContainer,
 object)
```

I suppose since you have the schema locally you could determine this by parsing the schema. To get the parent of any class, you'd look for 

```
neurodata_type_def: "[neurodata type]"
neurodata_type_inc: "[parent type]"
```

I suppose we could expose some sort of index for this so you don't have to compute it every time, but you still would need to parse the cached schema for any extensions

**Comment by magland** [comment]
@bendichter A prelim version of this is now working.

For now, I generate the inheritance rules using Python, using an example nwb file:
https://github.com/flatironinstitute/neurosift/blob/main/devel/create_neurodata_type_inheritance.ipynb

That generates this which is hard-coded:
https://github.com/flatironinstitute/neurosift/blob/main/gui/src/pages/NwbPage/neurodataSpec.ts

Then I check for inheritance when determining which view to open:
https://github.com/flatironinstitute/neurosift/blob/e54ec13bd20ed35f60935d893599547cc63ce864/gui/src/pages/NwbPage/NeurodataItemView/NeurodataItemView.tsx#L17-L28

Ideally, we'd read the spec from the nwb file (because this would handle different versions, and extensions), but I think hard-coding is the right choice for this stage of development because reading the spec is somewhat complicated and adds to the latency of the initial load.

I am closing this issue, but later on we can open a similar issue when we are ready to implement the more advanced spec loading.
