### ISSUE TITLE
red time selector line in slider does not have correct placement

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#19]
![image](https://github.com/flatironinstitute/neurosift/assets/844306/4c37cb1e-e501-458b-b80d-d4633cc4a51b)
I am selecting the time on the very end of the window, but the selector in the slider is at the center

**Comment by magland** [comment]
The issue here is that the visible time window is so small relative to the total recording duration that the bar would be too small to grab with the mouse -- so I make a larger grabbable bar (it's a somewhat different color - black instead of gray). So the red bar is in the correct location, but it's deceptive. One possibility is to just leave the bar super small (would be 1 pixel wide)... but then you wouldn't be able to drag it. Clicking on the slider moves the position also, so maybe it's not such a big deal.

Open to suggestions.
