### ISSUE TITLE
NWB: Render Position object

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#33]
https://flatironinstitute.github.io/neurosift/#/nwb?url=https://dandiarchive.s3.amazonaws.com/blobs/be4/594/be4594ef-f0db-43b4-b4fa-823927ee3b40

![image](https://github.com/flatironinstitute/neurosift/assets/844306/3f440258-4ed6-4aae-b560-a12e7bc1f99f)

![image](https://github.com/flatironinstitute/neurosift/assets/844306/27dd8dfb-72f4-4587-9cbd-64c6ca081997)

**Comment by magland** [comment]
This has been fixed in that the subitem is now visible, which is a SpatialSeries.

However, this particular example doesn't actually render because it uses timestamps rather than sampling rate. So I'll close this, and I'll work on this issue (which is going to be somewhat tricky):
https://github.com/flatironinstitute/neurosift/issues/27
