### ISSUE TITLE
spinner while data is loading

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#43]
I sometimes find it difficult to know whether there is no data or the data is still loading. I would like some sort of indicator while data is being drawn on the plot to indicate that the data is still loading.

I am imagining a small spinner on the upper right just inside the axes, though I think many designs could work here.

**Comment by magland** [comment]
I put a gray "Loading..." message in the upper left of the axes. I think this is less annoying than a spinner. We can improve the appearance in the future, or reposition the message. But I am going to close this issue since I think it's sufficient for now.


![Image](https://github.com/flatironinstitute/neurosift/assets/3679296/d97dafed-9e8a-4bfc-a1ec-82530f8bc1c2)

**Comment by bendichter** [comment]
LGTM!
