### ISSUE TITLE
BUG: error loading LFP in this example...

### ISSUE THREAD

**Issue by magland** [flatironinstitute/neurosift#63]
https://flatironinstitute.github.io/neurosift/?p=/nwb&url=https://dandiarchive.s3.amazonaws.com/blobs/b15/072/b1507274-5e2a-4f9a-8e40-177807b039ee

**Comment by CodyCBakerPhD** [comment]
Manual investigation of file from https://dandiarchive.org/dandiset/000576/draft/files?location=sub-01

shows no obvious problems aside from non-standard period character in the group name, but I wouldn't expect that to break anything per se

Only slightly unusual thing I notice is that it's written as floats instead of integers

**Comment by magland** [comment]
This has been resolved.
