### ISSUE TITLE
channel controller improvements

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/neurosift#82]
<img width="677" alt="image" src="https://github.com/flatironinstitute/neurosift/assets/844306/4ebce4eb-5104-4f2e-9d68-0fce2b142970">

I would prefer changing [<][>] to up and down arrows. I think of left/right as through time and up/down as through traces.

It's not clear from this controller how many electrodes there are. Could you add that?

Why have the # electrodes as a dropdown instead of a integer text entry field that only accepts positive integers?

**Comment by magland** [comment]
The first two items have been implemented.

I'm going to keep the # channels selector as it is because I think the user usually wants to jump to a particular number of channels, and I don't see the need to allow the user the added flexibility of specifying a specific number that is not one of the presets.

![Image](https://github.com/flatironinstitute/neurosift/assets/3679296/f7b85270-374a-482c-9c17-51a1dd4fdc4e)
