### ISSUE TITLE
[Feature] Shareable links to recreate precise views

### ISSUE THREAD

**Issue by CodyCBakerPhD** [flatironinstitute/neurosift#84]
It would be a super convenient feature to be able to generate a 'share' link that regenerates a view environment I've created on a particular S3 asset

Right now the workflow is to share the link to the file, together with instructions of what neurodata types to click on, and what range to view them over, possibly with a snapshot of what I'm personally looking at

But if someone could just follow the URL and it automatically creates the view, it could make it super easy for people to collaborate on a discovery during data exploration

**Comment by magland** [comment]
Thanks for the suggestion, I agree this would be super helpful.

The strategy that comes to mind is to embed the full state in the URL. However, if the state is complex (many tabs open, navigated to particular timepoints, etc.), this could end up making the url inconveniently long. An alternative is to persist the state in some database, which adds quite a bit of complexity to the app. Maybe the best way forward is to allow sharing a limited state, like a single tab.

**Comment by magland** [comment]
Another issue to consider is the possibility that the app might change in a way that breaks old links, which is annoying.

**Comment by bendichter** [comment]
I agree this would be very valuable. Persisting the state in a database is an interesting idea but I think I prefer the url. It does not rely on a database being maintained and it can be created so that it is transparent to the user what information is being passed.

As for long urls, you could do what Youtube does and offer the option of sharing the state (in their case just starting time of the video) or just the video link without any state.

<img width="932" alt="image" src="https://github.com/flatironinstitute/neurosift/assets/844306/24aa7edd-5dd5-459f-99cf-a8275a93399e">

<img width="510" alt="image" src="https://github.com/flatironinstitute/neurosift/assets/844306/7ed62e46-f8ca-4f4b-8425-b84ad13981b3">

We could similarly have a "share" link, which would allow you to include state variables. 

I guess in either case you would need to have each view class expose its full parameterization.

To get around the breaking issue, we could also pass the version of neurosift and keep around old major versions, though I don't think that's necessary yet while we are still getting our feet on the ground.

**Comment by CodyCBakerPhD** [comment]
@magland Looking great, was already super convenient for pointing you to the example tab in #89

**Comment by CodyCBakerPhD** [comment]
@magland Should I open a separate issue for tracking progress on sharing timestamped points in a series?

**Comment by magland** [comment]
@CodyCBakerPhD Oops, I closed prematurely. Reopening.

**Comment by magland** [comment]
@CodyCBakerPhD 

You can now save the selected time range and the current selected timepoint by checking the box when generating the shared URL, as in the following screenshot

![Image](https://github.com/flatironinstitute/neurosift/assets/3679296/3b18faac-9a4a-4955-9515-a85a5a1cee12)


And here's an example link

https://flatironinstitute.github.io/neurosift/?p=/nwb&url=https://dandiarchive.s3.amazonaws.com/blobs/544/745/5447455e-49ec-4ce0-9a64-4cad767bef7b&tab=neurodata-item:/processing/behavior/BehavioralTimeSeries/running_speed|TimeSeries&tab-time=90.90120528435017,98.9216642035915,92.86312435285117

(notice the tab-time query parameter)

**Comment by magland** [comment]
Closing, as this seems to be working.
